var a = "Airconditioning";
var d = "Domestic";
var h = "HVAC & Commercial";
var t = "Tools & Accessories";

var products = [
["Value Charging Hoses", "Value", t],
["Value Digital Clamp Meter", "Value", t],
["Value Digital Micron Gauge", "Value", t],
["Value Double Gauge Manifold", "Value", t],
["Value Flaring Tool", "Value", t],
["Value Hydraulic Expander", "Value", t],
["Value Manual Expander", "Value", t],
["Value Quick Couplers", "Value", t],
["Value Ratchet Spanner", "Value", t],
["Value Sealing Plier", "Value", t],
["Value Tubecutter", "Value", t],
["Value Tubebender", "Value", t],
["Value Vacuum Pump", "Value", t],
["AIPL PU Foam Spray", "AIPL", t],
["AIPL Aluminum Tape", "AIPL", t],
["AIPL Nitrile Foam Tape", "AIPL", t],
["AIPL Duct Tape", "AIPL", t],
["AIPL PVC Insulation Tape 48mm", "AIPL", t],
["AIPL BOPP Tape", "AIPL", t],
["AIPL AB80", "AIPL", t],
["Value Recovery Unit", "Value", t],
["Value Refrigerant Scale", "Value", t],
["Value Single Gauge Manifold", "Value", t],
["Value Deburring Tool", "Value", t],
["Value Capillary Tube Plier", "Value", t],
["Black Horse Access Valve", "Black Horse", t],
["Black Horse Condensers", "Black Horse", d],
["Danfoss Liquid Line Filter Drier", "Danfoss", h],
["Danfoss Expansion Valve", "Danfoss", h],
["Danfoss Temperature Controller", "Danfoss", h],
["Danfoss Shut-Off Valve", "Danfoss", h],
["Danfoss Ball Valve", "Danfoss", h],
["Danfoss Orifice", "Danfoss", h],
["Danfoss NRV Check Valve", "Danfoss", h],
["Danfoss Sight Glass", "Danfoss", h],
["Dosea Bottle Shelf", "Dosea", d],
["Dosea Fan Motor", "Dosea", d],
["Dosea ATM Timer", "Dosea", a],
["BP Refcool Can Tap Valve", "BP Refcool", t],
["BP Refcool Blend Vaporizer", "BP Refcool", t],
["BP Refcool Leak Locator", "BP Refcool", t],
["BP Refcool Extreme Ultra", "BP Refcool", t],
["BP Refcool Micro Bluvac", "BP Refcool", t],
["BP Refcool Drain Tabs", "BP Refcool", t],
["BP Refcool Acid Tabs", "BP Refcool", t],
["BP Refcool Evo Tabs", "BP Refcool", t],
["BP Refcool Kino Tabs", "BP Refcool", t],
["AIPL PVC Insulation Tape 18mm", "AIPL", t],
["DIJ Flare Nut Short Neck", "DIJ", t],
["DIJ Flare Tee", "DIJ", t],
["DIJ Flare Nut Long Neck", "DIJ", t],
["DIJ Reducing Tee", "DIJ", t],
["DIJ Dead Nut", "DIJ", t],
["DIJ Half Union Tee", "DIJ", t],
["DIJ Reducing Nut", "DIJ", t],
["DIJ Female Elbow", "DIJ", t],
["DIJ Flare Union", "DIJ", t],
["DIJ Female Coupling", "DIJ", t],
["DIJ Condenser Union", "DIJ", t],
["DIJ Charging Adapter", "DIJ", t],
["DIJ Half Union", "DIJ", t],
["DIJ Reducing Union", "DIJ", t],
["DIJ Carrier Adapter", "DIJ", t],
["DIJ Flare Seal Plug", "DIJ", t],
["DIJ Nurling Cap", "DIJ", t],
["DIJ Cylinder Adopter", "DIJ", t],
["DIJ Charging Union With Pin", "DIJ", t],
["DIJ Nitrogen Union", "DIJ", t],
["DIJ Gauge Adapter", "DIJ", t],
["DIJ Split Valve Cap", "DIJ", t],
["DIJ Flare Elbow", "DIJ", t],
["DIJ Flare Adapter", "DIJ", t],
["DIJ Half Union Elbow", "DIJ", t],
["DIJ Cylinder Valve", "DIJ", t],
["DIJ Ball Valve", "DIJ", t],
["Dosea Frost Free Fan Blades", "Dosea", a],
["Dosea Airconditioner Fan Blades", "Dosea", a],
["Dosea Shaded Pole Motor", "Dosea", a],
];
products.sort()
products.sort((a,b)=>{
	if(a[1] < b[1]){
		return -1
	} else if( a[1] > b[1]){
		return 1
	} else {
		return 0
	}});